# Generated by Django 5.1.4 on 2024-12-31 14:21

import django.core.validators
import django.db.models.deletion
import gestion_prep.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Catégorie d'article",
                'verbose_name_plural': "Catégories d'articles",
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Equipement',
                'verbose_name_plural': 'Equipements',
                'ordering': ['tag'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Train',
                'verbose_name_plural': 'Trains',
                'ordering': ['unite__site__nom', 'unite__nom', 'nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypePlatinage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Type de platinage',
                'verbose_name_plural': 'Types de platinage',
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_article', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('specification', models.TextField(blank=True, null=True)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix')),
                ('devise', models.CharField(blank=True, choices=[('EUR', 'Euro (€)'), ('USD', 'Dollar ($)'), ('GBP', 'Livre Sterling (£)'), ('DZD', 'Dinar Algérien (DZD)')], max_length=3, null=True, verbose_name='Devise')),
                ('unite_mesure', models.CharField(max_length=20)),
                ('quantite_initiale', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantite_stock', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('seuil_alerte', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('categorie_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='gestion_prep.categoriearticle')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['code_article'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to=gestion_prep.models.document_upload_path, verbose_name='Fichier')),
                ('remarque', models.CharField(blank=True, max_length=255, null=True, verbose_name='Remarque')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='gestion_prep.article')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_uploades', to=settings.AUTH_USER_MODEL)),
                ('equipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='gestion_prep.equipement')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='MouvementMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bmm', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Numéro BMM')),
                ('type_mouvement', models.CharField(choices=[('SORTIE_DEFINITIVE', 'Sortie définitive'), ('SORTIE_PRET', 'Sortie à titre de prêt'), ('ENTREE', 'Entrée')], max_length=20, verbose_name='Type de mouvement')),
                ('description_bmm', models.TextField(help_text='Description détaillée du mouvement', verbose_name='Description')),
                ('emetteur_recepteur', models.CharField(help_text="Nom de l'émetteur ou du récepteur", max_length=100, verbose_name='Émetteur/Récepteur')),
                ('departement_service', models.CharField(help_text='Département ou service concerné', max_length=100, verbose_name='Département/Service')),
                ('date_retour_prevue', models.DateTimeField(blank=True, help_text='Obligatoire pour les sorties à titre de prêt', null=True, verbose_name='Date de retour prévue')),
                ('date_retour_effective', models.DateTimeField(blank=True, null=True, verbose_name='Date de retour effective')),
                ('remarque', models.TextField(blank=True, help_text='Remarques ou notes supplémentaires', null=True, verbose_name='Remarque')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('equipement', models.ForeignKey(blank=True, help_text='Équipement concerné par le mouvement', null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_prep.equipement', verbose_name='Équipement')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Mouvement de matériel',
                'verbose_name_plural': 'Mouvements de matériel',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueMouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('CREATION', 'Création'), ('VALIDATION', 'Validation'), ('ANNULATION', 'Annulation')], max_length=20)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques_mouvement', to=settings.AUTH_USER_MODEL)),
                ('mouvement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='gestion_prep.mouvementmateriel')),
            ],
            options={
                'verbose_name': 'Historique de mouvement',
                'verbose_name_plural': 'Historiques de mouvement',
                'ordering': ['-date_action'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Platinage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repere', models.CharField(max_length=100, verbose_name='Repère')),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platinages', to='gestion_prep.article')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platinages', to='gestion_prep.equipement')),
                ('type_platinage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platinages', to='gestion_prep.typeplatinage')),
            ],
            options={
                'verbose_name': 'Platinage',
                'verbose_name_plural': 'Platinages',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('platinages', models.ManyToManyField(blank=True, related_name='phases', to='gestion_prep.platinage', verbose_name='Platinages')),
            ],
            options={
                'verbose_name': 'Phase',
                'verbose_name_plural': 'Phases',
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_stock', models.CharField(choices=[('MAGASIN', 'Magasin'), ('HORS_MAGASIN', 'Hors Magasin')], default='MAGASIN', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('emplacement', models.CharField(max_length=100)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='gestion_prep.site')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['nom'],
                'abstract': False,
                'unique_together': {('nom', 'type_stock', 'emplacement')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='gestion_prep.stock'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipements', to='gestion_prep.train'),
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unites', to='gestion_prep.site')),
            ],
            options={
                'verbose_name': 'Unité',
                'verbose_name_plural': 'Unités',
                'ordering': ['site__nom', 'nom'],
                'abstract': False,
                'unique_together': {('site', 'nom')},
            },
        ),
        migrations.AddField(
            model_name='train',
            name='unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trains', to='gestion_prep.unite'),
        ),
        migrations.CreateModel(
            name='LigneMouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Quantité')),
                ('stock_avant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Stock avant')),
                ('stock_apres', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Stock après')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_prep.article', verbose_name='Article')),
                ('mouvement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_prep.mouvementmateriel', verbose_name='Mouvement')),
            ],
            options={
                'verbose_name': 'Ligne de mouvement',
                'verbose_name_plural': 'Lignes de mouvement',
                'unique_together': {('mouvement', 'article')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('code_article', 'stock')},
        ),
        migrations.AlterUniqueTogether(
            name='train',
            unique_together={('unite', 'nom')},
        ),
    ]
