# Generated by Django 5.1.4 on 2025-01-02 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniteMesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, unique=True)),
                ('symbole', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Unité de mesure',
                'verbose_name_plural': 'Unités de mesure',
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='unite_mesure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='gestion_prep.unitemesure', verbose_name='Unité de mesure'),
        ),
    ]
